; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27024.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\ilyad\AppData\Local\Temp\.NETFramework,Version=v4.7.1.AssemblyAttributes.cpp"
